# Copyright (C) Angel Santamaria Navarro 
# All Rights Reserved 2024
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

/**:
  ros__parameters:
    gait:
      knee_orientation: ">>"
      pantograph_leg: false
      odom_scaler: 0.9
      max_linear_velocity_x: 0.50
      max_linear_velocity_y: 0.25
      max_angular_velocity_z: 1.0
      com_x_translation: 0.0
      swing_height: 0.04
      stance_depth: 0.00
      stance_duration: 0.25
      nominal_height: 0.4
    loop_rate: 1000.0
    use_sim_time: true
    base: spot/base_link
    # LINKS for SPOT
    left_front_links: ["spot/front_left_hip", "spot/front_left_upper_leg", "spot/front_left_lower_leg", "spot/front_left_ee"]
    left_hind_links: ["spot/rear_left_hip", "spot/rear_left_upper_leg", "spot/rear_left_lower_leg", "spot/rear_left_ee"]
    right_front_links: ["spot/front_right_hip", "spot/front_right_upper_leg", "spot/front_right_lower_leg", "spot/front_right_ee"]
    right_hind_links: ["spot/rear_right_hip", "spot/rear_right_upper_leg", "spot/rear_right_lower_leg", "spot/rear_right_ee"]
    # JOINTS for SPOT
    left_front_joints: ["spot/front_left_hip_x", "spot/front_left_hip_y", "spot/front_left_knee"]
    left_hind_joints: ["spot/rear_left_hip_x", "spot/rear_left_hip_y", "spot/rear_left_knee"]
    right_front_joints: ["spot/front_right_hip_x", "spot/front_right_hip_y", "spot/front_right_knee"]
    right_hind_joints: ["spot/rear_right_hip_x", "spot/rear_right_hip_y", "spot/rear_right_knee"]
